### PR TITLE
feat: main, favorite, statistic page mobile responsive design and fix favorite page final round error

### LINKED ISSUE #47: hearder design for each page
### issue
- 페이지별 header design이 미세하게 다름

### solution
- 하나로 통일하는 작업 필요

### LINKED ISSUE #52: favorite game final round and finish modal error
### issue
- final round가 종료된 후에 finish modal이 뜨는데, 이때 modal창이 뒤로 가려지는 현상 발생
image

### solution
z-index 추가

### PR DESCRIPTION
**Pull request by min-minnn**
### main page
image

### favorite page
image
image

#### favorite
image

#### timer
image

#### quiz
image

### header
image

### before
image

### after
image

## check list
- [x] main page
- [x] delete main page mouseover animation
- [x] favorite page
- [x] favorite page animation (select title size)
- [x] favorite statistic page
- [x] timer statistic page
- [x] quiz statistic page
- [x] header
- [x] fix favorite game final round error

### CODE REVIEW

**Comment by min-minnn** [comment]
@kim-song-jun Review plz

**Comment by min-minnn** [comment]
@kim-song-jun Review plz

**Comment by min-minnn** [comment]
@kim-song-jun Review plz

**Comment by min-minnn** [comment]
@kim-song-jun Review plz

**Review by kim-song-jun — COMMENTED** [review]
LGTM

**Pull request merged**
